### ISSUE TITLE
Hydrating problem when using react4xp-regions: DOM mismatch

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#44] opened 2020-03-21 14:20 UTC
When using Regions:

```
Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t<div data-portal-component-type=\"part\" id=\"parts_hello-react__main_0\"></div>\t\t\t\t\t\n" Client: "\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t<!--# COMPONENT /main/0 -->\t\t\t\t\t\n"
    in div (created by Region)
    in Region (created by Regions)
    in Regions
    in div
```

Still renders and hydrates, but ugly console message, and might cause other problems?

**Comment by ComLock** [comment] 2023-04-04 09:04
Duplicate of https://github.com/enonic/lib-react4xp/issues/33

**Closed by ComLock** 2023-04-04 09:04 UTC
Labels: bug
